---

- name: openvpn restart
  service: name=openvpn state=restarted

- name: openvpn pack clients
  command: tar cvzf {{openvpn_keydir}}/{{item.item.name}}.tgz -C {{openvpn_keydir}} {{item.item.name}}.crt {{item.item.name}}.key {{item.item.name}}.ovpn ca.crt
  when: item.changed
  with_items: "{{openvpn_clients_changed.results}}"
